# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-07 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20181207_2343'),
        ('partner', '0004_auto_20181207_2336'),
    ]

    operations = [
    ]
